### ISSUE TITLE
'andThen' infix operator returning EmittingHandler

### ISSUE THREAD

**Issue by tblakers** [jwstegemann/fritz2#126]
At present we have

```
class Applicator<A, X>(inline val execute: suspend (A) -> Flow<X>) {
    infix fun andThen(nextHandler: Handler<X>) = SimpleHandler<A> {
        nextHandler.execute(it.flatMapConcat(this.execute))
    }
```

Can be used as follows, eg to push another event onto a channel via ```offer```

```
   apply<> {
      // some actions
   } andThen handleAndOffer {
      offer(it)
   }
```

Unfortunately the resulting type is SimpleHandler, which does not implement Flow, and hence can't be subscribed to using ```handledBy```.

Can work around this by first assigning the ```handleAndOffer``` instance as a property (so that it has an ```EmittingHandler``` type) before composing after the action using ```andThen```. But would be nice if we could do this without the intermediate assignment. 
Perhaps by having an additional ```andThen``` overload that accepts an ```EmittingHandler``` and returns a Handler type that implements ```Flow```?

**Comment by jamowei** [comment]
Hi, you are totally right that we missed that. But in our next version 0.7 we already removed the `Applicator` and `apply` functions because we find out that we don't need them anymore. Instead we have made our `handle` functions suspendable so that you can e.g. call a remote API directly in your `handle()` or `handleAndOffer()` function.

So in your case you would write something like this:
```kotlin
val remote = remote("http://httpbin.org/get").acceptJson()

val store = object : RootStore<String>("") {
           val load = handleAndOffer<String> {
                val body = remote.get().getBody()
                offer(body) //offer to other handlers
                body // set as new model
            }
}
...
store.load handledBy otherStore.load
```
If you want to call the `store.load` handler without an user interaction (event registration), you can use the new `action()` function instead:
```kotlin
val remote = remote("http://httpbin.org/get").acceptJson()

val store = object : RootStore<String>("") {
           val load = handle<String> { action, model ->
                val body = remote.get(action).getBody()
                val origin = JSON.parse<dynamic>(body).origin
                origin
            }
}
...
action("?name=test") handledBy store.load
```
So there is no need for the `Applicator` and `apply{}` function anymore and the resulting code is much easier to read.
To view these code changes you can checkout fritz2/master branch. Hopefully we can release this soon ;-)
