### ISSUE TITLE
Fritz2 Not Available In Maven Central

### ISSUE THREAD

**Issue by napperley** [jwstegemann/fritz2#284]
When creating a new Kotlin JS project using Fritz2 v0.8 the framework requires JCenter to be used, however JCenter is in the process of being [discontinued](https://blog.gradle.org/jcenter-shutdown) and anything on Jcenter should be migrated to Maven Central. On Maven Central there are no Fritz2 artifacts.

There is less than one month to migrate all Fritz2 artifacts to Maven Central (the deadline is 31 March 2021). Why are there no Fritz2 artifacts available on Maven Central? Unless Fritz2 artifacts are available on Maven Central the latest versions of the framework won't be available to use in Kotlin JS projects, and eventually the framework will be **unusable** in any Kotlin JS project that uses the framework. This bug needs to be given the highest priority given the gravity of the JCenter situation.

**Comment by jamowei** [comment]
Hi, yes we know that we need to publish our artifacts to another repo, like Maven Central. When we are done with our current release of fritz2 0.9 which we are working on at the moment, we will investigate on that! For now our fritz2 libs will be available in jcenter until February 1 2022. But of course our plan is to move to another repo to provide our newest versions of fritz2  there.

**Comment by jwstegemann** [comment]
Just to ask: do you have any experience publishing a lib to maven central. On a first glance this seems to be much more complex than jcenter (which was the reason for us to choose this). So we could need some help from somebody experienced with the process...
Anyway you are right. Given the registration, keys, etc. this is really urgent.

**Comment by jillesvangurp** [comment]
An alternative option is to simply rsync a local deploy to a webserver. I do that with [one of my multiplatform projects](https://github.com/jillesvangurp/geogeometry). Users will have to add your web server as a repository but otherwise very straightforward to do.

To get in maven central, you'll have to follow this process: https://central.sonatype.org/pages/ossrh-guide.html

I'd advice to look at some projects that deploy there and look at what they are doing. Mostly the staging thing is annoying where you have to first stage artifacts and then release them. I think there are plugins that do that for gradle as doing it manually is tedious in their UI.

It takes some time for the approval to happen on the sonatype side. Last time I did this, it took a few days. I avoid them because it's just a bit of a pita to deal with this. I would recommend generating some pgp key and sticking it in github secrets.

**Comment by jwstegemann** [comment]
@jillesvangurp Thanks for the introduction. I started the process today by registering to sonatype...

**Comment by hpehl** [comment]
AFAIK https://kotest.io/ is in Maven central. Maybe you can take a look at their Gradle setup. 

I deployed some of my Maven projects (https://github.com/hal/elemento) to Maven central. Once you are registered and have all artifacts at hand, the actual deployment is not difficult.
