### ISSUE TITLE
Improve styling API

### ISSUE THREAD

**Issue by jamowei** [jwstegemann/fritz2#322]
Hey, this might come handy to you as well. I've written a small utility function that helps in keeping styled component DSL consistent with fritz2 components lib DSL (also I find this a lot more readable):
```kotlin
typealias StyledComponent<E> = RenderContext.(style: BoxParams.() -> Unit, block: E.() -> Unit) -> E

fun <E> styled(component: BasicComponent<E>): StyledComponent<E> = { style, block ->
  (component.styled(styling = style))(block)
}

//usage
fun RenderContext.preview() {
  styled(::div)({
   // div style
  }) {
   // div code and inner layout
    div {
      // child unstyled div
    } 
  }
}
```
written by Martynas Petuška

**Comment by jwstegemann** [comment]
I am sorry, but I cannot see a concrete advantage regarding readability here. Can you explain it to me? There are still the same elements used. You also use the exact same amount of brackets, colons, etc.
In my opinion it is more important to get the name of the styled element (div, etc.) to the front to increase readability because this is the information I need when reading code, not that is is styled.
Wouldn't it be a better approach to offer specialized factory functions for all elements in the styling module that offers an additional styling context parameter?

**Comment by jamowei** [comment]
Perhaps it is better then to duplicate the tag functions by creating an extension function for each:
```kotlin
fun TagContext.div(
    styling: Style<BoxParams>,
    baseClass: String? = null,
    id: String? = null,
    prefix: String = "css",
    content: Div.() -> Unit
): Div {
    val baseStyle = baseClass?.let { StyleClass(it) } ?: StyleClass.None
    val additionalStyle = StyleParamsImpl().apply(styling).cssClasses(prefix)
    return register(Div(id, (baseStyle + additionalStyle).name, job), content)
}
```


```kotlin
import dev.fritz2.styling.* // import is needed here!

fun main() {

    render {
        div({
            background { color { "red" } }
        }, baseClass = "test", id = "id", prefix = "hugo") {
            p({
                color { "yellow" }
            }) {
                +"Hello World"
            }
        }
    }
}
```

**Comment by jwstegemann** [comment]
I think the two-method approach is good.

Maybe we should introduce a package `dev.fritz2.styling.elements` (or something like this) you have to important when you want to use styled elements...
