### ISSUE TITLE
Embed "3rd party" Javascript component

### ISSUE THREAD

**Issue by mmokross** [jwstegemann/fritz2#344]
Is it possible to embed javascript components into the ui, if no fritz2-component is available for now? Like select2, taglify, others?

I don't have the experience and time right now to implement components, which I need, myself. Therefor I would like to use this shortcut. PatternFly for fritz2 is missing some critical components too.

I searched in the documentation, but couldn't find a solution for this. Maybe I just missed something?

**Comment by jamowei** [comment]
Hi, did you try this guide from Kotlin JS already?
https://kotlinlang.org/docs/using-packages-from-npm.html

In my opinion there is no standard way to embed a native JS component into fritz2, because there is no standard on JS side for it, except for WebComponents. If you want to embed these into your fritz2 project, you can do the following: 
https://docs.fritz2.dev/WebComponents.html
Complete example:
https://examples.fritz2.dev/webcomponent/build/distributions/index.html

Otherwise you need to wrap your native JS API in a small fritz2 component by yourself to use it in the fritz2 HTML-DSL.
Like described here: https://docs.fritz2.dev/Components.html

**Comment by mmokross** [comment]
Great! Thank your your detailed reply!
