### ISSUE TITLE
Enable SSR (server-side rendering) so that the fritz2 syntax can be used always (instead of kotlinx.html)

### ISSUE THREAD

**Issue by pabl0rg** [jwstegemann/fritz2#352]
Server-side rendering is a simple and classic paradigm when you don’t need much client-side interaction.  Kotlinx.html is good for this.

When you want to add interaction, you suddenly have to rewrite everything from kotlinx.html into fritz2 (or combine a static kotlinx.html page with the reactive fritz2 UI in some sub-ideal way).  

It would be great if we could use fritz2 syntax to declare the UI even when not doing any client-side rendering yet.

thanks

**Comment by chausknecht** [comment]
In general this sounds interesting!

But at the moment I have no idea at all, how this could ever be realized, as you would habe to drop all interaction from a fritz2 app and "magically" replace those with some ``<a href="...">`` links, to make a server call.

If you have a specific proposal, please feel free to add information / sources or further technical ideas!

I believe that the main purpose for fritz2 is to be the foundation for SPAs (being reactive and responsive)! As our time and resources are rather limited, we should focus to overcome some problems with serach engines we currently still have, and focus on issue #354. This might be one specific reason for someone to use server-side rendering (https://kotlinlang.slack.com/archives/C01CSNG1HJ4/p1619107483051800)

For static pages there are probably enough specilized tools like jekyll and alike, so that this seems also not to be a use case.
