### ISSUE TITLE
FormControl: switch() is registered as inputField

### ISSUE THREAD

**Issue by metin-kale-cf** [jwstegemann/fritz2#413]
When using different renderStrategies for inputField{} and switch(), switch{} is rendered using the inputField strategy.

In the FormControl the Switch-Component is registered with ControlNames.inputField as controlName
 
See:
https://github.com/jwstegemann/fritz2/blob/4ec80d3e31fb072a1fd132f16df7224c377f041c/components/src/jsMain/kotlin/dev/fritz2/components/formcontrol.kt#L247

**Comment by chausknecht** [comment]
This small bug was fixed while adding the slider to the formControl:
https://github.com/jwstegemann/fritz2/pull/387/commits/0be47515b24a45dab2c24f67ef036359d5ee0880#diff-c7141722d54e3c1499044e2011589948f8e4dfe6ead45088f24dd79ebf638b68R250

Good catch, even though there is little to zero impact due to this false piece of code (the false control name would only appear within the exception message).
