### ISSUE TITLE
nested stackUps/lineUps result in ignoring full width

### ISSUE THREAD

**Issue by CreatsheR** [jwstegemann/fritz2#441]
Like the title says there is a bug when you are using nested stackUps/lineUps.
It doesn't matter if you are using them mixed or multiple of one kind.

Working (but without the wanted vertical spacings):
```
@ExperimentalCoroutinesApi
fun main() {
    render {
        box({
            width { full }
        }) {
            lineUp {
                items {
                    label { +"Text" }
                }
            }
            lineUp {
                items {
                    label { +"Text" }
                }
            }
        }
    }
}
```
![image](https://user-images.githubusercontent.com/72187841/121651333-cb543580-ca9a-11eb-8994-5003a8053dd5.png)

Not Working:
```
@ExperimentalCoroutinesApi
fun main() {
    render {
        stackUp({
            width { full }
        }) {
            items {
                lineUp {
                    items {
                        label { +"Text" }
                    }
                }
                lineUp {
                    items {
                        label { +"Text" }
                    }
                }
            }
        }
    }
}
```
![image](https://user-images.githubusercontent.com/72187841/121651372-d5763400-ca9a-11eb-9d3c-5827e1d6d060.png)

I added borders and paddings for the screenshots, which are not in the above codings for better readability. They are, however, of no importance for the behavior.

One solution I found is to apply the attribute `align-items: stretch` to the outer stackUp/lineUp. But when I'm not wrong I shouldn't need to add this attribute, because in the code-documentation is an example with nested stackUps/lineUps.

**Comment by haukesomm** [comment]
Hi @CreatsheR, thanks for submitting the issue, I was able to reproduce the behavior described by you.

Both the `stackUp` and `lineUp` components use a CSS-flexbox internally which does not fill the available space on the cross-axis by default. As you said, this can explicitly be enabled by specifying the `align-items: stretch` attribute on the container.  
The stack-components do not have a specific width out of the box. Thus, their dimensions my change based on where they are placed. The same behavior can be seen with vanilla flexboxes as well.

I will close this issue for now as it seems like expected behavior.

Kind regards,
Hauke
