### ISSUE TITLE
There is no api-support/best practice for lazy validation

### ISSUE THREAD

**Issue by metin-kale** [jwstegemann/fritz2#450]
**Is your feature request related to a problem? Please describe.**
If i use the WithValidator Interface and a ComponentValidator the validation messages for all fields will be shown, even if they were not touched yet.

A more elegant way to validate a form is to show the validation messages only if the field was touched or the user presses the submit button.

**Describe the solution you'd like**
There should be a api support from fritz2 or at least a best practice in the Kitchensink to achieve lazy validation, because this behaviour is very common.

**Describe alternatives you've considered**
As a workaround i am currently tracking the changes in a custom Store with a Lens-Wrapper

    fun <X> sub(lens: Lens<T, X>): SubStore<T, T, X> =
        SubStore(this, lens, this, lens + buildLens("", { it }, { _, it ->
            touched = setOf(*touched.toTypedArray(), ".${lens.id}".trimEnd('.'))
            it
     }))

and filter out the validations for untouched fields with

    override val validator = object : ComponentValidator<T, P>() {
        override fun validate(data: T, metadata: P): List<ComponentValidationMessage> =
            baseValidator.validate(data, metadata).filter { !filterUntouched.value || touched.contains(it.id) }
    }

whereas filterUntouched is a flag to allow validating all fields, e.g. after Submit has been clicked.

This works, but is more a workaround than a proper solution for this problem.

**Comment by chausknecht** [comment]
Have you had a deeper look into the KitchenSink example?
This behaves exactly the way you want it - is uses additional metadata to achieve this.

I would argue that adding kind of metadata to a store like you did it, could be a cleaner solution. I would imagine it might be an approach to offer an additional action for ``sub`` extension, that enables one to change the store data even further, like setting an appropriate flag for a property (within the model I would prefer an independent mapping between touched and untouched properties - relying on the ID feels kinda smelly to me for a final advice or solution)

Perhaps the simplest solution could be a model with nullable values, whereas you can simply check within the validation code for none nullability and therefore interpret this as "validation ready" property. If this is not possible, you have to refer to a "untouched" or initial state, which you can use to ignore such values (like the KitchenSink example does).

**Comment by chausknecht** [comment]
> The example in the KitchenSink ignores Validation of fields, if they are blank. That means the error would be hidden, even if the user filled the field and cleared it afterwards, or if the field was initially filled and cleared afterwards. Yes, when submitting the Form and revalidating the Data with another Metadata, these Fields can still be catched, but it would be better to show it instantly.

Isn't this a contradiction or am I missunderstandig your claims? The KS example works fine imho and behaves exactly like you want such a form to behave or not?

> I also think the validator should be kept simple, it should not contain the logic, which of the UI elements were touched and which not. It should rather only rely on the data, to decide, whether is is valid or not.
> I would prefer this functionality to be in the FormControl.

I have conceptual problems with this! Think of some kind of middleware stuff like logging validation or stuff like that. If we just validate everything completly ignoring the UI context, then it becomes unclear, where the origin of some missing message is! It might be the validator not working, it might be some trouble with the "already touched UI component" filter - who knows?

It is totally ok to include UI-state into a model; after all those are all UI models ;-) So imho it is far better to have a tailored concept / recipe by using the validation and store mechanisms as they are.

Also you will add more complexity to the formControl, which already is more complex as it feels good. If you want to customize its behaviour or include your own control factories, you will probably increase the boilerplate and ceremony code to fulfill in order to guarantee a correct working!

Also you will have to decide whether to support different strategies then, because not everyone might want to evaluate the form in the way you propose. This would increase the complexity even more - or reduce the flexibility of the framework.

I would definitly appreciate some helping / supporting API for manipulating a model with UI state because of UI actions, but we have to consider very carefully which is the right layer to put this.

It is indead worth discussing and do some brainstorming with the whole team of course!

**Comment by jwstegemann** [comment]
I try to summarize our discussed solution from today:

- add a parameter `showValidation : Flow<Boolean>?` (or something like that) to `FormControl` defaulting to `null` (which results in showing the messages, too)
- add a field `touched: StateFlow<Boolean>` to every form-component that tracks if the component has been touched by the user. For an `InputField` touched could become true, if the input once had and lost focus. For other components this might be slightly different.
- Add a switch `showValidationOnlyIfTouched` to `Theme`
- `FormControl` can now set it's `showValidation` to it's child's `touched` automatically if desired
- when newly  rendering a `formGroup` the validation could to be triggered. Since no field has been touched then, no messages will be shown, but whenever you touch a field you will se the corresponding messages (sync validation to changes).

**Comment by Lysander** [comment]
No priority at the moment.
