### ISSUE TITLE
Weird bug in FormControl with multiple Switch/Checkboxes

### ISSUE THREAD

**Issue by metin-kale-cf** [jwstegemann/fritz2#501]
i created a blank fritz2 project using the template and added the components dependency to reproduce the issue with a minimal example:

the main()-Method looks like:

    fun main() {
        render {
            formControl {
                switch(value = storeOf(false)) {
                    label("Label")
                }
            }
    
            formControl {
                switch(value = storeOf(false)) {
                    label("Label")
                }
            }
        }
    }

when i click the second switch, the first switch will be toggled. i cant toggle the second switch at all. The same issue also occurs using checkboxes.

**Comment by chausknecht** [comment]
This is not really a bug - at least I have forseen this situation in https://github.com/jwstegemann/fritz2/issues/445#issuecomment-865034009

The problem is the missing *explicit* `id` of your stores! The default is an empty `String`:
```kotlin
open class RootStore<T>(
    initialData: T,
    override val id: String = "" // Default ist an empty String -> thus two stores created with `storeOf` without explicit id will lead to the same id!
) : Store<T> {
    // and so on
}
```

The label (the "invisible" one rendered by the `ControlRenderer` - your label definition is kinda wrong anyways ) will via `for` attribute refer to the first (?) rendered control. Obviously your browser has to determine somehow wich element is related. This might be defined somewhere or it is completly undefined behaviour and might difffer from browser to browser.

So it is always recommended to work with some proper `id` if working with `formControl`s. This is also mentioned within the [KS demo page](https://components.fritz2.dev/#FormControl):

> The formControl tries to determine a good default for the id parameter of its control, so that a rendered label can be connected with it. Thus if no value for the id is explicitly given, it relies on the id of the passed store, which will get its id by its RootStore or its parentSubStore chained by dots.
It is therefore recommended to always pass an id into a (root-)store at creation, so that the id value of a formcontrol's control is really unique!
Be aware that the same id must be used within an inspector for validation purposes!

(can be found in the section *Initial Store*)

This overall behavior is also recommended as [EFC 208](Effective-fritz2-Components#item-208-consider-the-stores-id-as-default-value-for-id-parameter)

That said: Unfortunately we have not documented the decision, why we did not want to offer a default value for a store's `id`! I am shure we have discussed this during the work on issue #445!

Does this help you? Does this solve your problem?

**Comment by metin-kale-cf** [comment]
In the SwitchComponent the ID will be generated, if it is null:
https://github.com/jwstegemann/fritz2/blob/38fba088e23cb917a0a125e060c9f89c1dc22ffb/components/src/jsMain/kotlin/dev/fritz2/components/switch/component.kt#L117

In the CheckBoxComponent the id is used as it is
https://github.com/jwstegemann/fritz2/blob/38fba088e23cb917a0a125e060c9f89c1dc22ffb/components/src/jsMain/kotlin/dev/fritz2/components/checkboxes/componentSingle.kt#L123

I think the null check could be extended with a empty-check, so whenever the id is null _or empty_, it should generate an id. 
I think it is quite common to create a RootStore using storeOf() and directly using it, most of the Documentation and Code Examples do not set id, so users will neither. This is a really confusing issue, because it is difficult to figure out, what the problem is.

**Comment by chausknecht** [comment]
> This is a really confusing issue, because it is difficult to figure out, what the problem is.

I totally agree! I will have to bring this discussion back in order to figure out, whether the enforcing of providing an id could be the solution or how to deal otherwise with this situation.

**Comment by jamowei** [comment]
@metin-kale-cf can you cross-check the changes I made in PR #503. In my opinion this should fix the problem and make id providing more clear. Thanks!
