### ISSUE TITLE
TypeAhead should allow Generic Types

### ISSUE THREAD

**Issue by metin-kale-cf** [jwstegemann/fritz2#516]
The newly added typeAhead component only allows to use Strings as Value. When using custom data objects a special mapping logic is needed.

I think the typeAhead should work similiar to a selectField, where you can use generic types and map the type to a string by passing a lambda expression to `label {}`

**Comment by chausknecht** [comment]
That is imho not enough. You would also need another function for the inverse operation (`parse`) like as for [Formats](https://docs.fritz2.dev/Format.html) as the new search pattern would need to get mapped back to the type `T` in order to perform the new search.

Do you have some specific use case for that? Would be nice to have some proper example in order to extract the best API options.

**Comment by metin-kale-cf** [comment]
In my case i am using a huge list of Jobs as data source. It should behave like a selectField, but only with a search. Only items of the given list are allowed to choose. Because of the amount of options, a selectField is not very useful.

As workaround i currently use a lens like:

                    val lens = buildLens<Job?, String>("",
                        { it?.value ?: "" },
                        { _, name -> jobs.find { it.value == name } })

But yes, you are right. In case somewant wants to allow custom values, so that the given options are only suggestions, we would need a inverse operation. 

In case of a String Type the parse is trivial, so when supporting generics, people who want to allow every input, had simply to use String as type as it is now. If Custom Input is now allowed, custom Types like Enums could be used.
