### ISSUE TITLE
tooltip is still displayed after trigger is destroyed

### ISSUE THREAD

**Issue by EvaBS** [jwstegemann/fritz2#548]
When a tooltip is displayed on a temporary element (button in this case) and this element is no longer rendered, the tooltip is still displayed even after routing to another page.

```
pushButton {
    tooltip(id = someId) {
        text("Remove this button and this text will be visible forever")
    }
    events {
        clicks.map { } handledBy deleteThisButton
    }
}
```
I'd expect the tooltip to disappear with the button.

**Comment by chausknecht** [comment]
This is truely some kind of misconception of the tooltip component right now, as each tooltip is rendered at a central position in the dom tree independently from the trigger element. So if the trigger gets deleted, the rendered content does not automatically disappear, because it is no child of the trigger!

This would require lots of work for the current popup base component to behave differently, so I am not sure we will fix this soon... 

But there is some "hacky" work around you could try to adapt: You need to artificially create some `mouseleave` event, as the tooltip's close mechanism is built upon that one:
```kotlin
val showStore = storeOf(true)
showStore.data.render {
    if (it) {
        pushButton { // we absolutly need a pushButton in order to have access to a fitting events context!
            text("Click me!")
            tooltip("You really just need to click on the button!") {}
            events {
                clicks.map {
                    // dirty hack: use the click event to trigger the "delete action" and emit some artificial mouse event to close the tooltip
                    // DOM-API's string based dispatching to the rescue :-D (tooltip's close mechanism is based upon `mousleave` event!)
                    domNode.dispatchEvent(MouseEvent("mouseleave"))
                    false
                } handledBy showStore.update
            }
        }
    }
}
```
This seems to work; if there is any timing based trouble, you might add some `delay()` call after the event dispatching and before the return of `map`.

Of course this is rather ugly, but should offer you a possibility to keep your UI design at it is (not adding tooltips to disappearing / page changing triggers is of course the other solution).

**Comment by EvaBS** [comment]
Thank you! I might try that if we really need that particular tooltip. For now I have removed it and benched the issue :-)
