### ISSUE TITLE
Running a slow suspend function on `Flow` that's to be rendered makes UI freeze

### ISSUE THREAD

**Issue by Lundez** [jwstegemann/fritz2#572]
Hi!

I'm running a slow `suspend` function (~4.5s) that's running a WASM method. The whole UI completely freezes. The code is something like

```kotlin
val store: RootStore
val otherStore: RootStore

render {
  img { src(otherStore.data) }

  store.data.map { data -> callSuspendFunction(data) } handledBy otherStore.update
}
```

How am I supposed to use coroutines correctly? I've tried using `withContext` and other solutions that don't help.

**Comment by chausknecht** [comment]
Hi :-)

Some questions immediately arises to me:
- Which version of fritz2 are you using?
- Are you sure that ``store`` gets new data so that the UI state would change after the first iteration? 
    To give you a running example inspired by your code, where the image will only change exactly once:
    ```kotlin
    val images = listOf(
        "https://www.fritz2.dev/images/fritz_info_1.jpg",
        "https://www.fritz2.dev/images/fritz_info_2.jpg"
    )

    val imageSource = storeOf(images.first())
    val imageToggle = storeOf(0)

    render {
        img { src(imageSource.data) }
        imageToggle.data.map { // it will forever be `0` ;-)
            delay(5000)
            images[(it + 1) % images.size]
        } handledBy imageSource.update
    }
    ```
    So, tailored to your example: What updates ``store``? (And possible how this is done)
- Is it possible that some exception is thrown within the ``map``-operations? This would cause the coroutine to "die" and if there is no more action that drives your UI state, there will be the impression that the UI is frozen (also only this one mapping is dead)
    ```kotlin
    render {
        img { src(imageSource.data) }
        imageToggle.data.map {
            delay(5000)
            images[(it + 1) % images.size]
            throw IllegalStateException("Bad thing has happened")
        } handledBy imageSource.update
    }
    ```

If this does not help you, we definitely need more details or a running example in order to tackle this incidence.

**Comment by Lundez** [comment]
Hi @chausknecht 

As usual I forget to provide one detail which was "obvious" in the context of my head. The UI only freezes during these 4.5s that it's running.

The flow is something along this line:

1. Upload Image File --> Store updated with b64-data (side-note: this became a ugly workaround as the `File`-component doesn't keep the full b64..)
2. `Img` has `src(b64Store)` and is then updated through 1.
3. `img.onload` override, as I need to extract `img.domNode.naturalWidth/Height` which isn't available until `onload` is completed, 
     - using the `Store` returns result too early meaning I don't know image dimensions
4. `img.onload` then updates a second `Store` which in turn I listen to data changes
5. When this data changes I run my slow WASM-function on the image data after a few operations to translate image into a `Tensor`.
6. This function outputs a new b64 which updates a second `Img` through a similar  `Store` as in 1. only that I now create the `b64` through a `canvas` element that I temporarily create

The full source-code is available at https://github.com/londogard/photo-fritz2/blob/master/src/jsMain/kotlin/app.kt (open-sourced today)
The code is pretty ugly, so would've wanted to clean it up until I share it 😆 Will try to shape it up tonight, but really the focus is not on code but running ONNX in the browser ^^,

**Comment by Lundez** [comment]
Code is running at https://photo-fritz2.pages.dev/

**Comment by Lundez** [comment]
Regarding Exceptions, I can't see any in the console and the code works out after 4.5s of frozen UI, I get my updated image - hence I don't think that's the issue 😄

**Comment by chausknecht** [comment]
There is one aspect that triggers me immediately during skimming through the code:
You are creating a ``Tag`` within an event-handling chain ([Canvas](https://github.com/londogard/photo-fritz2/blob/master/src/jsMain/kotlin/app.kt#L115)). This is definitely not recommended.

I have tried your application, and it feels quite brittle. Sometimes I got exceptions occurring, sometimes nothing happened at all after the image has been shown. Sometimes there appeared a black image below the uploaded one with the download button below.

I am still not sure, what UI freeze means to you - imho there is no UI that could be change / being reactive during the process? What is expected to happen? How do you pin down the freezing? (And after all: What is the goal after all - just curious! )

**Comment by Lundez** [comment]
This is the app in its prowest, using dark images:
[![image](https://user-images.githubusercontent.com/7490199/151333334-22f04592-dd65-438e-8d0f-cc8e7a1a6dc4.png)
](https://user-images.githubusercontent.com/7490199/151235880-2546faa6-5798-48b4-84b9-db71c20808d8.gif)

The idea I wanted to achive was to have a spinner load during the processing of the image. I tried using the buttons `loading(Flow<Boolean>)` with its sibling `loadingText(text: String)`. But they don't "activate" as the whole app freezes...


P.S. Large images (larger than 1080x1080) takes a pretty long while to actually process. Using a 3k x 3k image took >20s I think.

**Comment by chausknecht** [comment]
You should do the long-running process inside a custom handler and apply a [tracker](https://docs.fritz2.dev/Tracking.html) to it, which you could then use for showing a spinner.

Imho that should solve the problem.

For testing whether the app freezes, you could simply add some other UI elements, like some button that add toggles some texts or alike. If this reacts, then the UI is not frozen ;-)

**Comment by chausknecht** [comment]
Nice App btw :-)

**Comment by Lundez** [comment]
Following up, using `loads handledBy { println("LOADED") }` inside `img`-element I get `Unexpected type while listening for `load` events`.

This does not happen for `mouseenters` as example.

Another thing, the second time I run my model through the `tracker` the button does not show as loading. 
I think the GUI does do freeze and that the tracker only shows first time because of race condition. I can see my mouse being frozen in "hand-mode" that is done selecting file. That's until the file is processed.

Could you look at new code and see if my handling is still bad..?

**Comment by Lundez** [comment]
Hi @chausknecht I added a `delay(100)` and the loading spinner started working again... I think there's some kind of race condition between the `Flow`'s. At least when I use a `tracker`.

Does this make sense in any way? Is there any way I can make sure that my inference logic runs on a separate thread or that is not possible through the browser?

**Comment by chausknecht** [comment]
The result of the tracking operation still throws an exception - this is not good: https://github.com/londogard/photo-fritz2/blob/master/src/jsMain/kotlin/app.kt#L56

You should definitly catch it!

You mean the delay declared [here](https://github.com/londogard/photo-fritz2/blob/master/src/jsMain/kotlin/app.kt#L33)? I do not understand why this should be helpful...

Without the spinner does not appear?

**Comment by Lundez** [comment]
I throw because I want to see the app crash, which I don't... I'll replace it with a alert and `orNull` which is handled. But it's not really the point right now. 😄 

> You mean the delay declared [here](https://github.com/londogard/photo-fritz2/blob/master/src/jsMain/kotlin/app.kt#L33)? I do not understand why this should be helpful...

Without `delay(60)` the spinner is not shown the second time I run the code, potentially because of some type of race-condition in `Flow`'s?
By adding `delay(60)` I have the spinner run for each transform, rather than simply the first.

Does this make sense?

**Comment by chausknecht** [comment]
I can confirm, that adding the ``delay`` *enhances* the chances, that the browser's event-loop gets enough time for the rendering of the spinner.

After dicussing and investigating your issue (current version) with some colleagues, we have arrived to the conclusion, that the execution of the inference session in [line 43](https://github.com/londogard/photo-fritz2/blob/master/src/jsMain/kotlin/app.kt#L43) simply brings the whole system to its limit:
![grafik](https://user-images.githubusercontent.com/70946811/153011657-7f7af220-40bd-42cb-a4e8-49ef3a1f4b2f.png)
The underlying WASM routines obviously take too longe time for arriving at some break point, where the event-loop can consume the next rendering task.

Imho this is no fritz2 issue, as we cannot modify the browser's event-loop ;-)

I have the following suggestions for you:
1.) Try to let the conversion run within a [web-worker](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API) and synchronize this inside a handler. This would be cool, if you would arrive to some kind of recipe, which we would love to feature or spread ;-)
2.) Try to figure out, if the [configuration](https://github.com/londogard/photo-fritz2/blob/master/src/jsMain/kotlin/onnx/ONNX.kt#L13) of the session can be tuned, so that the process will last longer, but with less resources (system threads for example)

I am sorry, that I cannot provide some super cool simple solution - as I really am impressed by the app itself! Really cool stuff, what you have built. So I would appreciate if you will give us feedback about some solution to the problem.

If you agree with me, that is is not a fritz2 issue, please close this one or tell me to close it :-)

**Comment by Lundez** [comment]
Thanks, that's really insightful.

I was afraid the issue was something along the lines of what you're saying. I'll see if I can get some recipe figured out.
Last time I looked at building a PWA I believe that you need a new JS-file per webworker. 
Hopefully I'll solve that one, and of course share it here 😄

A huge thank you for helping me come further in this issue! 🙏

**Comment by Lundez** [comment]
P.S. one of the issues was my function call `min`, being incredibly slow.

According to https://stackoverflow.com/a/8885656 function calls repeatedly is slow.. :O
