### ISSUE TITLE
`.loads` on `HTMLImageElement` is not always a `UIEvent`

### ISSUE THREAD

**Issue by Lundez** [jwstegemann/fritz2#578]
**Describe the bug**
`.loads` expect to always receive a `UIEvent` which is not true. As

> UiEvent if generated from a user interface, Event otherwise.

source: [w3schools](https://www.w3schools.com/jsref/event_onload.asp)

**To Reproduce**
1. Load image by supplying a b64-string from a file input
2. Attach `loads.events handledBy { println("This does not work") }`
3. Validate error in console

**Expected behavior**
To not fail, e.g. don't expect and force `UIEvent` type for `loads` event.

**Screenshots**
![image](https://user-images.githubusercontent.com/7490199/151509433-ca7f90cd-6952-452c-9d1f-5cc2a01b1cad.png)
The first line is me calling `domNode.addEventListener("load", {println("Event and type: ${it.type} ${it} ${it is UIEvent}")})` manually. 
Second line is your code crashing in `WithEvents<Out T: Element>`
```kotlin
private inline fun <reified E : Event> subscribe(type: EventType<E>): DomListener<E, T> = DomListener(
        callbackFlow {
            val listener: (Event) -> Unit = {
                if (it is E) { // <-- failing because of this
                    trySend(it.unsafeCast<E>())
                } else {
                    console.error("Unexpected type while listening for `${type.name}` events")
                }
            }
            domNode.addEventListener(type.name, listener)

            awaitClose { domNode.removeEventListener(type.name, listener) }
        })
```

**Comment by chausknecht** [comment]
We already had some issues like this in the past :-(

Unfortunately, the documentation of events is kinda irritating across the web. We strongly relied on MDN in the past, but obviously the former is not precise in all circumstances.

Perhaps the w3schools might fit better?
At least we could also rely on the official spec: https://www.w3.org/TR/uievents/#event-type-load
Unfortunately, the official doc is also not right in all cases: https://www.w3.org/TR/uievents/#event-type-input. We have learned the hard way, that Chrome and Safari offer ``Events`` instead of ``InputEvents`` when selecting from a ``datalist``!

I would love to extend this issue therefor and expect a PR to review all predefined standard events in ``dev.fritz2.dom.html.Events`` object. We should hopefully be able to choose the right level of type strictness for the bunch then to avoid such annoying issues in the future (as long as the standard does not change, or some browser vendors simply ignore the standard...)

## Advice for fixing
- Check all events in ``Events`` object!
- in doubt rely on the less strict type!
