### ISSUE TITLE
Consider basic React support

### ISSUE THREAD

**Issue by NoUsernameProvided** [jwstegemann/fritz2#870]
Would be great to have sort of support for 3rd party react components. Could something like in kvision where you are allowed to use them only inside a react { } scope.

Use case to me personally is being able to use
https://ui.shadcn.com/
and
https://www.radix-ui.com/

out of the box.  It's not for some Reac-specific "mega" features, it just so happens that there's a big community that develops for react.

**Comment by Lysander** [comment]
I do not really understand the use-case honestly.

React targets the same use-cases as fritz2 does - but simply in another technical way and with JS (or TypeScript). So you can choose to use fritz2 or react - I do not see the advantages of mixing both *within* one fritz2-app.

(You could "mix" them within a page with separate micro-frontends of course)

So it would be great, if you can elaborate your use-case in order to discuss about technical ways for some integration.

**Comment by Lysander** [comment]
As there seems to be not much interest on this, I close the issue for now.

If you still want to elaborate and discuss, feel free to open it again :-)
