### ISSUE TITLE
Modal behaviour

### ISSUE THREAD

**Issue by rm3dom** [jwstegemann/fritz2#906]
**Describe the bug**

Created a repo here to demonstrate and explain the issue:

[rm3dom/fritz2-modal](https://github.com/rm3dom/fritz2-modal)

Maybe I am doing it wrong: 

* The modal works fine as long as the user does not use the browsers history to navigate, when a user navigates using the browser the store's job (flow) dies and the modal stays open. User has to hard refresh. Mapping the router state also does not work for me because the job/flow dies before the modal could do its thing.

* Moving the stores state globally works for navigation, but creating the modal in a render causes the modal content to accumulate on the portal stack, and gets rendered multiple times.

The example repo demonstrates this, there are two "pages", on with a local store (job) and the other with a global store. They each have their own problems.

The only way forward that I can see is to move all my state globally or not using the modal. Hopefully I am just missing something, or using it wrong, however fritz2 normally just works so this one got me.

**Comment by Lysander** [comment]
Thx for reporting that - we will have a look at it!

**Comment by Lysander** [comment]
Further investigations led us to the solution, that the PR #907 will fix - thx again for your report!

This "only" solves one aspect of your problems: Modals triggered by some reactively dependent flow will now reflect the same reactive changes. That means any modal that gets some `Store<Boolean>` (or at least some `Flow<Boolean>`) passed by the `openState`-data-binding, will be removed from the `PortalStack` if the depending store or flow is cancelled. Such cancellation will always occur, if the store or flow is created inside of some `MountPoint`, which itself is created by any of our `render*`-functions. If a new value appears on the `render`-flow, the mountpoint will cancel all child jobs. The solution is exactly based upon that semantic!

The other problem is not really a bug, but a design / programming error:

You can choose to implement modals with locally, reactivley affected triggers (e.g. `page1` in your example and solved by the upcoming PR), or some *global* modal with obviously also some global trigger.

You have mixed both up - that is simply not "solveable" in any way we can think of! That is because the `modal`-factory will always be called if the `page2` case will reactively be rendered. We cannot recognize inside the `Modal`-initialization process, whether that modal already exist or not! As the trigger-flow is *global*, it will never be cancelled and so it will never get removed from the `PortalStack`!

If you think about the problem clearely, then imho this can be easily avoided: Just stick to some local or either global modal and you are fine :-)

Concerning your example I have created a gist, that demonstrates that:
https://gist.github.com/Lysander/72a780d6270f16eb5c437a87374896ac

(Beware that this design is not really good - I misuse the global store inside the `page`-rendering to determine, whether the modal should be created or not)

**Comment by rm3dom** [comment]
Thank you, your a machine!

Really only need a local modal to work. The global issues I stumbled upon while panic hacking.

**Comment by Lysander** [comment]
Thx :-)

We try hard to improve the framework and reach the 1.0 stable for christmas :-)

Because I am curious:
Do you use the SNAPSHOT version of fritz2 already? 
The latter uses Kotlin 2.0 already an I am curious, whether you might have encountered any problems or also benefits?

**Comment by rm3dom** [comment]
I can give it a go. I have a lot on my plate, so I'm just trying to hit
features at this moment.

I'm invested in Fritz2 now, I have a lot in it already, and I have to
upgrade to K2 at some point.

**Comment by Lysander** [comment]
The next RC - and maybe the Last before final 1.0 Release - will definitely be based upon Kotlin 2.0. So we investigate already how this behaves with internal projects. But of course we appreciate any feedback 😃
